spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sapa?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Qaz!@#12
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      ##静态映射路径
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations: classpath:mapper/*.xml
##上传文件地址
file:
  path: D:\nginx\img\
